trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"      
  displayName: Install rust
- script: cargo build --all
  displayName: Cargo build
- script: cargo test --all
  displayName: Cargo test
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: './target/debug/server'
    artifactName: server
